# Generated by Django 4.2.8 on 2023-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_coupons', '0002_mscoupon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscoupon',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
