# Generated by Django 4.2.5 on 2023-11-27 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsMapstarContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('request', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 27, 14, 19, 21, 394295), null=True)),
            ],
        ),
    ]
