# Generated by Django 4.2.5 on 2023-11-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msmapstarcontact',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
