# Generated by Django 4.2.5 on 2023-12-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_payment_method', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mspaymentmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
