# Generated by Django 4.2.8 on 2023-12-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_payment_method', '0003_mspaymentmethod_main_qr_code_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mspaymentmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment-method/'),
        ),
        migrations.AlterField(
            model_name='mspaymentmethod',
            name='main_QR_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='payment-method/'),
        ),
    ]
