# Generated by Django 4.2.8 on 2023-12-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_payment_method', '0004_alter_mspaymentmethod_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mspaymentmethod',
            name='sequence',
            field=models.IntegerField(default=100),
        ),
    ]
