# Generated by Django 4.2.5 on 2023-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msproperty',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
