# Generated by Django 4.2.5 on 2023-11-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0002_msproperty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='msproperty',
            name='included_benefits',
            field=models.TextField(default=''),
        ),
    ]
