# Generated by Django 4.2.5 on 2023-11-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0004_alter_msproperty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='msproperty',
            name='property_standard_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
