# Generated by Django 4.2.5 on 2023-11-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0006_msproperty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='msproperty',
            name='rest_room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='msproperty',
            name='total_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
