# Generated by Django 4.2.8 on 2023-12-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0008_msproperty_other_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msproperty',
            name='bedroom_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
