# Generated by Django 4.2.8 on 2024-01-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0009_msproperty_bedroom_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='msproperty',
            name='location_iframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
