# Generated by Django 4.2.5 on 2023-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_company', '0003_mscompany_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscompany',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
