# Generated by Django 4.2.5 on 2023-12-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_company', '0004_mscompany_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscompany',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
