# Generated by Django 4.2.5 on 2023-12-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_company', '0005_alter_mscompany_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscompany',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mscompany',
            name='tiktok_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mscompany',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mscompany',
            name='zalo_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
