# Generated by Django 4.2.5 on 2023-11-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ms_province', '0001_initial'),
        ('ms_job', '0003_msjob_job_title'),
        ('ms_job_experience', '0001_initial'),
        ('ms_social_media', '0001_initial'),
        ('ms_certificate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(default='male', verbose_name=(('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')))),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('joining_date', models.DateField()),
                ('certificate_subject', models.CharField(max_length=255)),
                ('university_name', models.CharField(max_length=255)),
                ('expected_salary', models.IntegerField()),
                ('job_position', models.TextField(blank=True, null=True)),
                ('cv_file', models.BinaryField(blank=True, editable=True, null=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_certificate.mscertificate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_job.msjob')),
                ('job_experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_job_experience.msjobexperience')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_province.msprovince')),
                ('social_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_social_media.mssocialmedia')),
            ],
        ),
    ]
