# Generated by Django 4.2.8 on 2023-12-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property_slider_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mspropertysliderimage',
            name='image',
            field=models.ImageField(upload_to='property-slider/'),
        ),
    ]
