# Generated by Django 4.2.5 on 2023-11-18 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_company', '0002_remove_mscompany_owner'),
        ('ms_customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscustomer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_company.mscompany'),
        ),
    ]
