# Generated by Django 4.2.8 on 2023-12-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_customer', '0003_alter_mscustomer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscustomer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/'),
        ),
    ]
