# Generated by Django 4.2.8 on 2023-12-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_customer', '0005_mscustomer_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
