# Generated by Django 4.2.8 on 2023-12-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_customer', '0007_mscustomer_customer_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscustomer',
            name='partner_type',
            field=models.CharField(blank=True, null=True, verbose_name=(('individual', 'Cá nhân'), ('agency', 'Agency'))),
        ),
    ]
