# Generated by Django 4.2.5 on 2023-11-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msjob',
            name='code',
        ),
    ]
