# Generated by Django 4.2.5 on 2023-11-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_job_title', '0001_initial'),
        ('ms_job', '0002_remove_msjob_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='msjob',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_job_title.msjobtitle'),
        ),
    ]
