# Generated by Django 4.2.8 on 2023-12-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_job', '0003_msjob_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='msjob',
            name='code',
            field=models.CharField(default=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
