# Generated by Django 4.2.8 on 2023-12-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_job', '0004_msjob_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msjob',
            name='code',
        ),
    ]
