# Generated by Django 4.2.8 on 2023-12-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_job', '0005_remove_msjob_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='msjob',
            name='code',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
