# Generated by Django 4.2.5 on 2023-12-04 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ms_property', '0008_msproperty_other_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsAccountPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tiền thuê')),
                ('type', models.CharField(default='inbound', verbose_name=(('inbound', 'Thu'), ('outbound', 'Chi')))),
                ('state', models.CharField(default='draft', verbose_name=(('draft', 'Nháp'), ('paid', 'Đã thu'), ('refund', 'Hoàn thu'), ('cancel', 'Hủy')))),
                ('total_amount', models.FloatField()),
                ('create_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms_property.msproperty')),
            ],
        ),
    ]
