# Generated by Django 4.2.5 on 2023-11-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0005_msproperty_property_standard_price'),
        ('ms_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msservices',
            name='property',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ms_property.msproperty'),
        ),
    ]
