# Generated by Django 4.2.5 on 2023-11-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0005_msproperty_property_standard_price'),
        ('ms_services', '0003_alter_msservices_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msservices',
            name='property',
        ),
        migrations.AddField(
            model_name='msservices',
            name='property',
            field=models.ManyToManyField(to='ms_property.msproperty'),
        ),
    ]
