# Generated by Django 4.2.5 on 2023-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_services', '0006_alter_msservices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msservices',
            name='price',
            field=models.FloatField(default=False, null=True),
        ),
    ]
