# Generated by Django 4.2.5 on 2023-11-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0005_msproperty_property_standard_price'),
        ('ms_services', '0007_alter_msservices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msservices',
            name='price',
            field=models.FloatField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='msservices',
            name='property_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ms_property.msproperty'),
        ),
    ]
