# Generated by Django 4.2.5 on 2023-11-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_services', '0008_alter_msservices_price_alter_msservices_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msservices',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
