# Generated by Django 4.2.5 on 2023-11-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_services', '0010_alter_msservices_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='msservices',
            name='image',
            field=models.ImageField(default=False, upload_to='images/'),
            preserve_default=False,
        ),
    ]
