# Generated by Django 4.2.5 on 2023-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_services', '0012_alter_msservices_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='msservices',
            name='is_full_package',
            field=models.BooleanField(default=False),
        ),
    ]
