# Generated by Django 4.2.5 on 2023-12-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_destination', '0002_msdestination_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='msdestination',
            name='priority',
            field=models.IntegerField(default=1000),
        ),
    ]
