# Generated by Django 4.2.8 on 2023-12-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_country', '0003_mscountry_icon'),
        ('ms_destination', '0004_msdestination_destination_background_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msdestination',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_country.mscountry'),
        ),
    ]
