# Generated by Django 4.2.5 on 2023-11-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ms_job', '0003_msjob_job_title'),
        ('ms_province', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('date_expire', models.DateField()),
                ('job_type', models.CharField(choices=[('remote', 'Remote'), ('full_time', 'Full-time'), ('part_time', 'Part-time'), ('hybrid', 'Hybrid')], default='full_time')),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác'), ('not_require', 'Không yêu cầu')], default='not_require')),
                ('job_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField()),
                ('applicant_requirement', models.TextField()),
                ('job_compensation', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_job.msjob')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_province.msprovince')),
            ],
        ),
    ]
