# Generated by Django 4.2.5 on 2023-11-14 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property', '0005_msproperty_property_standard_price'),
        ('ms_property_condition', '0002_alter_mspropertycondition_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mspropertycondition',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ms_property.msproperty'),
        ),
    ]
