# Generated by Django 4.2.5 on 2023-11-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_property_condition', '0003_alter_mspropertycondition_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mspropertycondition',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
