# Generated by Django 4.2.5 on 2023-11-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ms_coupons', '0001_initial'),
        ('ms_destination', '0001_initial'),
        ('ms_property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('no_adult', models.IntegerField()),
                ('no_children', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_country', models.CharField(max_length=100)),
                ('customer_request', models.TextField()),
                ('visita_anterior', models.CharField(max_length=100)),
                ('total_amount', models.FloatField()),
                ('taxed_total_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=100)),
                ('coupon_ids', models.ManyToManyField(to='ms_coupons.mscoupon')),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms_destination.msdestination')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms_property.msproperty')),
            ],
        ),
    ]
