# Generated by Django 4.2.5 on 2023-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_services', '0012_alter_msservices_image'),
        ('ms_booking_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbooking',
            name='extra_services_ids',
            field=models.ManyToManyField(to='ms_services.msservices'),
        ),
    ]
