# Generated by Django 4.2.5 on 2023-11-16 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_payment_method', '0001_initial'),
        ('ms_booking_booking', '0002_msbooking_extra_services_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msbooking',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_payment_method.mspaymentmethod'),
        ),
    ]
