# Generated by Django 4.2.5 on 2023-11-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0003_alter_msbooking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbooking',
            name='state',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
