# Generated by Django 4.2.5 on 2023-11-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0004_msbooking_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msbooking',
            name='no_adult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='msbooking',
            name='no_children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
