# Generated by Django 4.2.5 on 2023-11-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0005_alter_msbooking_no_adult_alter_msbooking_no_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msbooking',
            name='taxed_total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
