# Generated by Django 4.2.5 on 2023-12-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0006_alter_msbooking_taxed_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msbooking',
            name='state',
            field=models.CharField(default='draft', max_length=100, verbose_name=(('draft', 'Nháp'), ('reserve', 'Giữ phòng'), ('book', 'Khách đặt'), ('done', 'Hoàn thành'), ('cancel', 'Hủy'))),
        ),
    ]
