# Generated by Django 4.2.5 on 2023-12-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0007_alter_msbooking_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msbooking',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='msbooking',
            name='customer_city',
        ),
        migrations.RemoveField(
            model_name='msbooking',
            name='customer_country',
        ),
        migrations.RemoveField(
            model_name='msbooking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='msbooking',
            name='taxed_total_amount',
        ),
        migrations.RemoveField(
            model_name='msbooking',
            name='visita_anterior',
        ),
        migrations.AlterField(
            model_name='msbooking',
            name='customer_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
