# Generated by Django 4.2.5 on 2023-12-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0008_remove_msbooking_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbooking',
            name='booking_code',
            field=models.CharField(default=False, unique=True),
            preserve_default=False,
        ),
    ]
