# Generated by Django 4.2.5 on 2023-12-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0009_msbooking_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbooking',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
