# Generated by Django 4.2.8 on 2023-12-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0010_msbooking_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msbooking',
            name='state',
            field=models.CharField(default='done', max_length=100, verbose_name=(('done', 'Hoàn thành'), ('cancel', 'Hủy'))),
        ),
    ]
