# Generated by Django 4.2.8 on 2023-12-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_customer', '0006_mscustomer_is_active'),
        ('ms_booking_booking', '0011_alter_msbooking_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbooking',
            name='create_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ms_customer.mscustomer'),
        ),
    ]
