# Generated by Django 4.2.8 on 2023-12-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0012_msbooking_create_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msbooking',
            name='state',
            field=models.CharField(default='done', max_length=100, verbose_name=(('confirm', 'Xác nhận'), ('done', 'Hoàn thành'), ('cancel', 'Hủy'))),
        ),
    ]
