# Generated by Django 4.2.8 on 2023-12-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0013_alter_msbooking_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msbooking',
            name='state',
            field=models.CharField(default='done', max_length=100, verbose_name=(('waiting_confirm', 'Chờ xác nhận'), ('confirm', 'Xác nhận'), ('done', 'Hoàn thành'), ('cancel', 'Hủy'))),
        ),
    ]
