# Generated by Django 4.2.8 on 2023-12-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_booking', '0014_alter_msbooking_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msbooking',
            name='destination_id',
        ),
    ]
