# Generated by Django 4.2.5 on 2024-01-04 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_customer', '0008_mscustomer_partner_type'),
        ('ms_booking_booking', '0015_remove_msbooking_destination_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbooking',
            name='cancel_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mscustomer_cancelcustomer', to='ms_customer.mscustomer'),
        ),
        migrations.AddField(
            model_name='msbooking',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
