# Generated by Django 4.2.5 on 2024-01-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_customer', '0008_mscustomer_partner_type'),
        ('ms_booking_booking', '0016_msbooking_cancel_customer_msbooking_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbooking',
            name='confirm_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mscustomer_confirmcustomer', to='ms_customer.mscustomer'),
        ),
    ]
