# Generated by Django 4.2.8 on 2024-01-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ms_booking_source', '0001_initial'),
        ('ms_booking_booking', '0017_msbooking_confirm_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='msbooking',
            name='booking_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ms_booking_source.msbookingsource'),
        ),
    ]
